# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160310_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.AddField(
            model_name='venue',
            name='address_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='address_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='address_3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='address_4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='post_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
