# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:58
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tutor_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='pic',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/tutors'),
        ),
    ]
