# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:20
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20160313_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
