# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_venue_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='position',
        ),
    ]
