# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_auto_20160310_2350'), ('courses', '0003_auto_20160310_2353'), ('courses', '0004_auto_20160310_2355'), ('courses', '0005_course'), ('courses', '0006_daterange'), ('courses', '0007_tutor_pic'), ('courses', '0008_auto_20160313_1558'), ('courses', '0009_auto_20160313_1559'), ('courses', '0010_venue_position'), ('courses', '0011_remove_venue_position')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address_1', models.CharField(blank=True, max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('address_3', models.CharField(blank=True, max_length=100)),
                ('address_4', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('blurb', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('number_of_weeks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='pic',
            field=models.ImageField(upload_to='images/tutors'),
        ),
    ]
