# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160317_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
