# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160310_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='post_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
