# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160310_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('blurb', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Venue')),
            ],
        ),
    ]
