# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20160313_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='pic',
            field=models.ImageField(upload_to='images/tutors'),
        ),
    ]
